import type { DashboardData, Investment, Invoice, TreasuryHistory } from '../types';

export const mockInvestments: Investment[] = [
  {
    id: '1',
    company_name: 'Al-Rajhi Capital',
    document_name: 'Annual Report 2024.pdf',
    recommendation: 'approve',
    status: 'approved',
    financial_analysis: {
      revenue: 2500000000,
      profitability: 18.5,
      roe: 22.3,
      roa: 8.7,
      debt_equity_ratio: 0.45,
      summary: 'Strong financial performance with consistent growth',
    },
    risk_assessment: {
      strategic_risk: 3,
      financial_risk: 2,
      operational_risk: 3,
      compliance_risk: 2,
      shariah_risk: 1,
      overall_rating: 2.2,
      summary: 'Low risk profile with strong governance',
    },
    shariah_compliance: {
      halal_screening: 'pass',
      riba_compliance: 'compliant',
      gharar_assessment: 'Minimal uncertainty in contracts',
      overall_status: 'compliant',
      notes: 'Fully Shariah compliant operations',
    },
    final_memo: 'Recommended for investment. Strong fundamentals and Shariah compliance.',
    created_at: '2025-01-15T08:00:00Z',
    approved_by: 'CFO',
    approved_at: '2025-01-16T10:30:00Z',
  },
  {
    id: '2',
    company_name: 'Saudi Aramco Sukuk',
    document_name: 'Sukuk Prospectus Q1 2025.pdf',
    recommendation: 'approve',
    status: 'pending',
    financial_analysis: {
      revenue: 450000000000,
      profitability: 32.1,
      roe: 28.5,
      roa: 15.2,
      debt_equity_ratio: 0.25,
      summary: 'Exceptional financial strength',
    },
    risk_assessment: {
      strategic_risk: 2,
      financial_risk: 1,
      operational_risk: 2,
      compliance_risk: 1,
      shariah_risk: 1,
      overall_rating: 1.4,
      summary: 'Very low risk - government backed',
    },
    shariah_compliance: {
      halal_screening: 'pass',
      riba_compliance: 'compliant',
      overall_status: 'compliant',
    },
    created_at: '2025-01-18T09:00:00Z',
  },
  {
    id: '3',
    company_name: 'Islamic Development Bank',
    document_name: 'IDB Green Sukuk 2025.pdf',
    recommendation: 'approve',
    status: 'pending',
    financial_analysis: {
      revenue: 8500000000,
      profitability: 12.3,
      roe: 15.8,
      roa: 6.2,
      debt_equity_ratio: 0.35,
    },
    risk_assessment: {
      strategic_risk: 2,
      financial_risk: 2,
      operational_risk: 2,
      compliance_risk: 1,
      shariah_risk: 1,
      overall_rating: 1.6,
    },
    shariah_compliance: {
      halal_screening: 'pass',
      riba_compliance: 'compliant',
      overall_status: 'compliant',
    },
    created_at: '2025-01-17T14:00:00Z',
  },
  {
    id: '4',
    company_name: 'Etihad Airways',
    document_name: 'Aviation Sukuk Proposal.pdf',
    recommendation: 'hold',
    status: 'pending',
    financial_analysis: {
      revenue: 5200000000,
      profitability: 8.5,
      roe: 10.2,
      roa: 4.1,
      debt_equity_ratio: 0.72,
    },
    risk_assessment: {
      strategic_risk: 5,
      financial_risk: 6,
      operational_risk: 5,
      compliance_risk: 3,
      shariah_risk: 2,
      overall_rating: 4.2,
    },
    shariah_compliance: {
      halal_screening: 'conditional',
      riba_compliance: 'review',
      overall_status: 'requires_review',
      notes: 'Requires restructuring of some financing arrangements',
    },
    created_at: '2025-01-16T11:00:00Z',
  },
  {
    id: '5',
    company_name: 'ACME Holdings',
    document_name: 'Investment Proposal 2025.pdf',
    recommendation: 'reject',
    status: 'rejected',
    risk_assessment: {
      strategic_risk: 8,
      financial_risk: 7,
      shariah_risk: 6,
      overall_rating: 7,
    },
    shariah_compliance: {
      halal_screening: 'fail',
      riba_compliance: 'non_compliant',
      overall_status: 'non_compliant',
      notes: 'Interest-based financing detected',
    },
    created_at: '2025-01-14T10:00:00Z',
    rejected_by: 'Shariah Board',
    rejected_at: '2025-01-14T16:00:00Z',
    rejection_reason: 'Non-compliant with Shariah principles - interest-based debt structure',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    invoice_number: 'INV-2025-001',
    vendor_name: 'Saudi IT Solutions',
    amount: 45000,
    currency: 'SAR',
    gl_code: '6100-IT',
    description: 'Cloud infrastructure services Q1',
    status: 'pending',
    due_date: '2025-02-15',
    created_at: '2025-01-18T08:00:00Z',
  },
  {
    id: '2',
    invoice_number: 'INV-2025-002',
    vendor_name: 'Legal Advisors LLP',
    amount: 125000,
    currency: 'SAR',
    gl_code: '6200-LEGAL',
    description: 'Sukuk structuring legal fees',
    status: 'pending',
    due_date: '2025-02-10',
    created_at: '2025-01-17T14:30:00Z',
  },
  {
    id: '3',
    invoice_number: 'INV-2025-003',
    vendor_name: 'Riyadh Office Supplies',
    amount: 8500,
    currency: 'SAR',
    gl_code: '6300-ADMIN',
    description: 'Office supplies and stationery',
    status: 'approved',
    created_at: '2025-01-16T10:00:00Z',
    approved_by: 'Finance Manager',
    approved_at: '2025-01-16T15:00:00Z',
  },
  {
    id: '4',
    invoice_number: 'INV-2025-004',
    vendor_name: 'Deloitte Saudi Arabia',
    amount: 350000,
    currency: 'SAR',
    gl_code: '6400-AUDIT',
    description: 'Annual audit services 2024',
    status: 'pending',
    due_date: '2025-02-28',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: '5',
    invoice_number: 'INV-2025-005',
    vendor_name: 'Al-Madinah Catering',
    amount: 12000,
    currency: 'SAR',
    gl_code: '6500-MEALS',
    description: 'Board meeting catering services',
    status: 'approved',
    created_at: '2025-01-14T11:00:00Z',
    approved_by: 'Admin Manager',
    approved_at: '2025-01-14T14:00:00Z',
  },
  {
    id: '6',
    invoice_number: 'INV-2025-006',
    vendor_name: 'Gulf Insurance Co.',
    amount: 85000,
    currency: 'SAR',
    gl_code: '6600-INS',
    description: 'Annual takaful premium',
    status: 'posted',
    created_at: '2025-01-12T08:00:00Z',
    approved_by: 'CFO',
    approved_at: '2025-01-13T10:00:00Z',
  },
];

export const mockTreasuryHistory: TreasuryHistory[] = [
  {
    id: '1',
    current_balance: 2450000,
    analysis: 'Healthy liquidity position. Cash inflow from sukuk distributions received.',
    created_at: '2025-01-19T09:00:00Z',
  },
  {
    id: '2',
    current_balance: 2180000,
    analysis: 'Moderate decrease due to quarterly vendor payments.',
    created_at: '2025-01-18T09:00:00Z',
  },
  {
    id: '3',
    current_balance: 2350000,
    analysis: 'Stable position maintained. Minor operational expenses.',
    created_at: '2025-01-17T09:00:00Z',
  },
  {
    id: '4',
    current_balance: 2520000,
    analysis: 'Dividend income received from portfolio investments.',
    created_at: '2025-01-16T09:00:00Z',
  },
  {
    id: '5',
    current_balance: 2100000,
    analysis: 'Large payment processed for infrastructure project.',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: '6',
    current_balance: 2650000,
    analysis: 'Strong cash position. Consider sukuk investment opportunities.',
    created_at: '2025-01-14T09:00:00Z',
  },
  {
    id: '7',
    current_balance: 2400000,
    analysis: 'Regular operational expenses. Position remains healthy.',
    created_at: '2025-01-13T09:00:00Z',
  },
];

export const mockDashboardData: DashboardData = {
  investments: mockInvestments,
  treasury: {
    current_balance: 2450000,
    last_updated: '2025-01-19T09:00:00Z',
    forecast: [
      { date: '2025-01-20', projected_balance: 2400000, inflows: 50000, outflows: 100000 },
      { date: '2025-01-21', projected_balance: 2350000, inflows: 30000, outflows: 80000 },
      { date: '2025-01-22', projected_balance: 2500000, inflows: 200000, outflows: 50000 },
      { date: '2025-01-23', projected_balance: 2480000, inflows: 40000, outflows: 60000 },
      { date: '2025-01-24', projected_balance: 2550000, inflows: 100000, outflows: 30000 },
    ],
    alerts: [
      {
        type: 'success',
        message: 'Balance above optimal threshold. Consider sukuk investment.',
        timestamp: '2025-01-19T09:00:00Z',
      },
      {
        type: 'info',
        message: 'Monthly treasury report generated successfully.',
        timestamp: '2025-01-18T14:00:00Z',
      },
      {
        type: 'warning',
        message: 'Large payment scheduled for next week - SAR 350,000',
        timestamp: '2025-01-17T10:00:00Z',
      },
    ],
    history: mockTreasuryHistory,
  },
  invoices: mockInvoices,
  summary: {
    pending_investments: 3,
    approved_investments: 1,
    pending_invoices: 3,
    total_invoice_value: 625500,
  },
};
